# Generated by Django 5.2.1 on 2025-05-10 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=254)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('A', 'Administrador'), ('B', 'Barbero'), ('U', 'Usuario')], default='U', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Cancelada'), ('R', 'Realizada')], default='P', max_length=1)),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbershop.servicios')),
                ('barbero', models.ForeignKey(limit_choices_to={'rol': 'B'}, on_delete=django.db.models.deletion.CASCADE, related_name='citas_barbero', to='barbershop.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_usuario', to='barbershop.usuario')),
            ],
        ),
    ]
