# Generated by Django 5.2.1 on 2025-05-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
